FROM haskell:8.0
MAINTAINER Alex Brandt <alunduil@alunduil.com>

RUN cabal update

WORKDIR /usr/local/src/collection-server

COPY ./collection-server.cabal /usr/local/src/collection-server/collection-server.cabal
RUN cabal install --only-dependencies

COPY . /usr/local/src/collection-server
RUN cabal install

ENTRYPOINT [ "collection-server" ]
